/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.enfore.gradleintro;

import com.enfore.gradleintro.models.User;
import com.google.gson.Gson;

public class Library {
    public static void main(String[] args) {
        User user = new User("Jane", "Doe");
        System.out.println(new Gson().toJson(user));
    }
}
